import { Platform, StyleSheet } from 'react-native';
import { adminC, adminTheme } from './adminTheme';

export { adminC, adminTheme, adminContentBgWeb } from './adminTheme';

export const adminStyles = StyleSheet.create({
  pageTitle: {
    fontSize: 26,
    fontWeight: '700',
    color: adminTheme.textPrimary,
    letterSpacing: -0.5,
    marginBottom: 4,
  },
  pageSubtitle: {
    fontSize: 14,
    color: adminTheme.textSecondary,
    marginBottom: 24,
    lineHeight: 20,
  },
  card: {
    backgroundColor: adminTheme.surface,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: adminTheme.border,
    padding: 20,
    marginBottom: 16,
    ...(Platform.OS === 'web' ? ({ boxShadow: adminTheme.shadow } as object) : {}),
  },
  cardTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: adminTheme.textPrimary,
    marginBottom: 14,
  },
  statLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: adminTheme.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  statHint: {
    fontSize: 13,
    color: adminTheme.textMuted,
  },
  label: {
    fontSize: 11,
    fontWeight: '600',
    color: adminTheme.textSecondary,
    marginBottom: 6,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  input: {
    backgroundColor: adminTheme.surface,
    borderWidth: 1,
    borderColor: adminTheme.border,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 14,
    color: adminTheme.textPrimary,
    marginBottom: 14,
  },
  btnPrimary: {
    backgroundColor: adminTheme.neon,
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 10,
    alignItems: 'center',
  },
  btnPrimaryText: {
    color: adminTheme.contentBg,
    fontWeight: '700',
    fontSize: 14,
  },
  btnSecondary: {
    backgroundColor: adminTheme.surfaceMuted,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: adminTheme.border,
  },
  btnSecondaryText: {
    color: adminTheme.neon,
    fontWeight: '600',
    fontSize: 13,
  },
  btnDanger: {
    backgroundColor: adminTheme.dangerSoft,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#FECACA',
  },
  btnDangerText: {
    color: adminTheme.danger,
    fontWeight: '600',
    fontSize: 13,
  },
  tableHeader: {
    flexDirection: 'row',
    paddingVertical: 10,
    paddingHorizontal: 12,
    backgroundColor: adminTheme.surfaceMuted,
    borderRadius: 8,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: adminTheme.border,
  },
  tableHeaderCell: {
    fontSize: 10,
    fontWeight: '700',
    color: adminTheme.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  tableRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: adminTheme.border,
  },
  tableCell: {
    fontSize: 14,
    color: adminTheme.textPrimary,
  },
  badge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    alignSelf: 'flex-start',
  },
  badgeText: {
    fontSize: 11,
    fontWeight: '700',
  },
  alertInfo: {
    backgroundColor: adminTheme.infoSoft,
    borderWidth: 1,
    borderColor: adminTheme.borderStrong,
    borderRadius: 10,
    padding: 12,
    marginBottom: 16,
  },
  alertInfoText: {
    fontSize: 13,
    color: adminTheme.neon,
    lineHeight: 18,
  },
});
